config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  resources :recipes do
    put :favorite, on: :member
  end
  devise_for :users

  root 'home#home'
  get 'categories' => 'category#index', :as => 'category'
  get 'category/:id' => 'category#subcategories', :as =>'subcategories'
  get 'category/:id/list' => 'category#list', :as => 'recipes_of_category'
  get '/user/:id' => 'user#profil', as: 'user'
  post '/recipes/:id' => 'comment#create'
  get '/user/:id/recipes' => 'user#recipes', :as => 'user_recipes'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.is? :admin
      can :manage, Recipe
      can :manage, User
    else if user.is? :default
      can [:read, :create, :favorite], Recipe
      can [:update, :destroy], Recipe, :user_id => user.id
      can :read, User, :id => user.id
    else
      can :read, Recipe
      cannot :create, Recipe
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_id, presence: true
  validates :recipe_id, presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :recipe
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_many :recipes
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, presence: true
  validates :image, presence: true
  validates :time, numericality: {only_integer: true}, presence: true
  validates :quantity, numericality: {only_integer: true}, presence: true
  validates :ingredients, presence: true
  validates :instructions, presence: true


  #attr_accessible :image
  belongs_to :user
  belongs_to :level
  belongs_to :subcategory
  has_many :comments
  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user
  ratyrate_rateable "instructions"
  mount_uploader :image, ImageUploader
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  has_many :recipes
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :name, presence: true
  has_many :recipes
  has_many :comments
  has_many :favorite_recipes
  has_many :favorites, through: :favorite_recipes, source: :recipe
  ratyrate_rater

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  Roles = [ :admin , :default ]

  def is?( requested_role )
    self.role == requested_role.to_s
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @last_recipes = Recipe.last(3)
  end



end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => true
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  respond_to :html


  def index
    @recipes = User.find(current_user.id).recipes
    respond_with(@recipes)
  end

  def show
    respond_with(@recipe)
  end

  def new
    if user_signed_in?
      @subcategories ||= []
      @categories = Category.all
      @categories.each do |category|
       sub = category.subcategories
       sub.each do |subcat|
          @subcategories << Category.new(name: category.name + '/' +subcat.name, id: subcat.id)
       end
      end
      @recipe = Recipe.new
      respond_with(@recipe)
    else
      redirect_to "/"
    end

  end

  def edit
    @subcategories ||= []
    @categories = Category.all
    @categories.each do |category|
      sub = category.subcategories
      sub.each do |subcat|
        @subcategories << Category.new(name: category.name + '/' +subcat.name, id: subcat.id)
      end
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.valid?
      Cloudinary::Uploader.upload(recipe_params[:image])
    else
      @subcategories ||= []
      @categories = Category.all
      @categories.each do |category|
        sub = category.subcategories
        sub.each do |subcat|
          @subcategories << Category.new(name: category.name + '/' +subcat.name, id: subcat.id)
        end
      end
    end
    @recipe.save
    respond_with(@recipe)
  end

  def update

      @recipe.update(recipe_params)
      @subcategories ||= []
      @categories = Category.all
      @categories.each do |category|
        sub = category.subcategories
        sub.each do |subcat|
          @subcategories << Category.new(name: category.name + '/' +subcat.name, id: subcat.id)
        end
      end
    respond_with(@recipe)
  end

  def destroy
    @recipe.destroy
    respond_with(@recipe)
  end

  # Add and remove favorite recipes
  # for current_user
  def favorite
    type = params[:type]
    @recipe = Recipe.find(params[:id])
    if type == "favorite"
      #current_user.favorites << @recipe
      current_user.favorites << @recipe
      redirect_to :back, notice: 'Sikeresen kedvencnek jelölted: ' + @recipe.name

    elsif type == "unfavorite"
      current_user.favorites.delete(@recipe)
      redirect_to :back, notice: 'Sikeresen törölted a kedvencek közül: '+@recipe.name

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :time, :level_id, :subcategory_id, :quantity, :ingredients, :instructions, :image).merge(user_id: current_user.id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def profil
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end

  def recipes
    @recipes = User.find(params[:id]).recipes
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def nl2br(s)
    s.gsub(/\n/, '<br>')
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe, html: { multipart: true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= @recipe.errors.count %> hiba miatt nem sikerült a recept mentése:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
    <%= f.label :category %><br />
    <%= f.collection_select :subcategory_id, @subcategories, :id, :name %><br /><br />
    <%= f.label :recipe_name %><br />
    <%= f.text_field :name, size: "51" %><br /><br />
    <%= f.label :image %><br />
    <%= f.file_field :image %><br />
    <%= f.label :time %><br />
    <%= f.text_field :time, size: "51" %><br /><br />
    <%= f.label :difficulty %><br />
    <%= f.collection_select(:level_id, Level.all,:id,:name) %>
    <br/><br/>
    <%= f.label :quantity %><br/>
    <%= f.text_field :quantity %><br /><br />
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients, cols: "50", rows: "10"  %><br /><br />
    <%= f.label :instructions %><br />
    <%= f.cktext_area :instructions %><br /><br />
</div>
  <div class="actions">
    <%= f.submit "Küldés" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Recept módosítása</h1>

<%= render 'form' %>

<%= link_to 'Vissza', recipes_path %>

app/views/recipes/index.html.erb
<h1>Receptjeim</h1>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe %></td>
        <% if can? :update, recipe %>
            <td><%= link_to 'Módosítás', edit_recipe_path(recipe) %></td>
        <% else %>
            <th colspan="1"></th>
        <% end %>
        <% if can? :destroy, recipe %>
            <td><%= link_to 'Törlés', recipe, method: :delete, data: { confirm: 'Biztos vagy benne??' } %></td>
        <% else %>
            <th colspan="1"></th>
        <% end %>
        <td><%= rating_for recipe, "instructions", :star => 5 %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/recipes/new.html.erb
<h1>Új recept</h1>

<%= render 'form' %>

<%= link_to 'Receptjeim', recipes_path %><br/>
<%= link_to 'Vissza', _back_url %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
    <% if @recipe.favorited_by.exists?(current_user.id) %>
        <h1><%= @recipe.name %></h1> <%= link_to raw('<span class="fa-stack fa-2x"><i class="fa fa-heart fa-stack-1x"></i><i class="fa fa-bolt fa-stack-1x fa-inverse"></i></span>'), favorite_recipe_path(type: "unfavorite"), method: :put, alt: "Eltávolítás a kedvencek közül." %>
    <% else %>
        <h1><%= @recipe.name %></h1> <%= link_to raw('<span class="fa-stack fa-2x"><i class="fa fa-heart fa-stack-1x"></i></span>'),   favorite_recipe_path(type: "favorite"), method: :put, alt: "Hozzáadás a kedvencekhez." %>
    <% end %>
<% end %>
<br />
<% if !user_signed_in? %>
    <h1><%= @recipe.name %></h1>
<% end %>

<%= rating_for @recipe, "instructions", :star => 5 %>
<div class="recipe-image img-responsive">
  <%= image_tag(@recipe.image.url, height: "200px") %>
</div>
<% if can? :update, @recipe %>
    <%= link_to 'Módosítás', edit_recipe_path(@recipe) %> |
<% end %>
<%= link_to 'Vissza', _back_url %>
<div>
  <p><i class="fa fa-clock-o"></i> <%= @recipe.time %> perc   |   <i class="fa fa-tachometer"> Nehézségi fok:</i> <%= Level.find(@recipe.level).name %></p>
</div>

<div>
  <h3>Hozzávalók:</h3>
  <h5><i class="fa fa-users"> </i> <%= @recipe.quantity %> személyre</h5>
  <%= raw nl2br(h(@recipe.ingredients)) %>
</div>
<br/>
<legend>Elkészítés:</legend>

<div class="leiras">
  <%= raw @recipe.instructions %>
</div>
<%= render :partial => 'recipes/comments/form' %>
<%= render :partial => 'recipes/comments/comments' %>