config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  resources :recipes do
    put :favorite, on: :member
  end
  devise_for :users

  root 'home#home'
  get 'categories' => 'category#index', :as => 'category'
  get 'category/:id' => 'category#subcategories', :as =>'subcategories'
  get 'category/:id/list' => 'category#list', :as => 'recipes_of_category'
  get '/user/:id' => 'user#profil', as: 'user'
  post '/recipes/:id' => 'comment#create'
  get '/user/:id/recipes' => 'user#recipes', :as => 'user_recipes'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.is? :admin
      can :manage, Recipe
      can :manage, User
    else if user.is? :default
      can [:read, :create, :favorite], Recipe
      can [:update, :destroy], Recipe, :user_id => user.id
      can :read, User, :id => user.id
    else
      can :read, Recipe
      cannot :create, Recipe
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_id, presence: true
  validates :recipe_id, presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :recipe
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_many :recipes
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, presence: true
  validates :image, presence: true
  validates :time, numericality: {only_integer: true}, presence: true
  validates :quantity, numericality: {only_integer: true}, presence: true
  validates :ingredients, presence: true
  validates :instructions, presence: true


  #attr_accessible :image
  belongs_to :user
  belongs_to :level
  belongs_to :subcategory
  has_many :comments
  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user
  ratyrate_rateable "instructions"
  mount_uploader :image, ImageUploader
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  has_many :recipes
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :name, presence: true
  has_many :recipes
  has_many :comments
  has_many :favorite_recipes
  has_many :favorites, through: :favorite_recipes, source: :recipe
  ratyrate_rater

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  Roles = [ :admin , :default ]

  def is?( requested_role )
    self.role == requested_role.to_s
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to :back
  end
  def comment_params
    params.require(:comment).permit(:content, :recipe_id).merge(user_id: current_user.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @last_recipes = Recipe.last(3)
  end



end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => true
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def profil
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end

  def recipes
    @recipes = User.find(params[:id]).recipes
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def nl2br(s)
    s.gsub(/\n/, '<br>')
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/profil.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @user.name %></h2>
<div class = "adatok">
    <p><span class="fa fa-at"></span> E-mail: <%= @user.email %></p>
    <p><span class="glyphicon glyphicon-list-alt"></span> Beküldött receptek száma: <%= @user.recipes.count %> <%= link_to 'Listázd', user_recipes_path %></p>
    <p><span class="fa fa-comment"></span> Hozzászólások száma: <%= @user.comments.count %></p>
    <p><span class="glyphicon glyphicon-calendar"></span> Regisztrált: <%= @user.created_at %></p>
    <p><span class="glyphicon glyphicon-calendar"></span> Utoljára itt járt: <%= @user.last_sign_in_at %></p>
</div>
<br />
<div class="kedvencek">
  <h3> <span class="fa fa-heart"> Kedvencnek jelölt receptjei:</span></h3>
    <table class="table table-hover">
      <% @favorites.each do |favorite| %>
          <tr>
              <td><%= link_to favorite.name, favorite %></td>
              <td><%= link_to User.find(favorite.user_id).name, user_path(favorite.user_id)  %></td>
              <td><%= rating_for favorite, "instructions", :star => 5 %> </td>
              <td><%= link_to raw('<span class="fa-stack fa-2x"><i class="fa fa-heart fa-stack-1x"></i><i class="fa fa-bolt fa-stack-1x fa-inverse"></i></span>'), favorite_recipe_path(favorite, type: "unfavorite"), method: :put %></td>
          </tr>
      <% end %>
    </table>
</div>

app/views/user/recipes.html.erb
<h3><%= User.find(params[:id]).name %> által beküldött receptek</h3>

<div class="receptjei">
  <table class="table table-condensed table-responsive">
    <thead>
    <tr>
      <td>Név</td>
      <td>Értékelés</td>
      <td>Hozzászólások száma</td>
    </tr>
    </thead>
    <% @recipes.each do |recipe| %>
        <tr>
          <td><%= link_to recipe.name, recipe %></td>
          <td><%= rating_for recipe, "instructions", :star => 5 %></td>
          <td><%= recipe.comments.count %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Bejelentkezés", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Regisztráció", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Elfelejtette a jelszavát?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Nem kapta meg a megerősítési utasításokat?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Nem kapta meg a feloldási utasításokat?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Bejelentkezés a #{provider.to_s.titleize} segítségével.", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>