config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
  resources :recipes do
    put :favorite, on: :member
  end
  devise_for :users

  root 'home#home'
  get 'categories' => 'category#index', :as => 'category'
  get 'category/:id' => 'category#subcategories', :as =>'subcategories'
  get 'category/:id/list' => 'category#list', :as => 'recipes_of_category'
  get '/user/:id' => 'user#profil', as: 'user'
  post '/recipes/:id' => 'comment#create'
  get '/user/:id/recipes' => 'user#recipes', :as => 'user_recipes'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.is? :admin
      can :manage, Recipe
      can :manage, User
    else if user.is? :default
      can [:read, :create, :favorite], Recipe
      can [:update, :destroy], Recipe, :user_id => user.id
      can :read, User, :id => user.id
    else
      can :read, Recipe
      cannot :create, Recipe
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_id, presence: true
  validates :recipe_id, presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :recipe
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_many :recipes
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, presence: true
  validates :image, presence: true
  validates :time, numericality: {only_integer: true}, presence: true
  validates :quantity, numericality: {only_integer: true}, presence: true
  validates :ingredients, presence: true
  validates :instructions, presence: true


  #attr_accessible :image
  belongs_to :user
  belongs_to :level
  belongs_to :subcategory
  has_many :comments
  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user
  ratyrate_rateable "instructions"
  mount_uploader :image, ImageUploader
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  has_many :recipes
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :name, presence: true
  has_many :recipes
  has_many :comments
  has_many :favorite_recipes
  has_many :favorites, through: :favorite_recipes, source: :recipe
  ratyrate_rater

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  Roles = [ :admin , :default ]

  def is?( requested_role )
    self.role == requested_role.to_s
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @last_recipes = Recipe.last(3)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def nl2br(s)
    s.gsub(/\n/, '<br>')
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <!-- <a class="navbar-brand" href="#">WebSiteName</a> -->
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Kezdőlap', root_path %></li>
        <li><%= link_to 'Receptek', category_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to 'Receptjeim', recipes_path %></li>
            <li><%= link_to 'Recept küldés', new_recipe_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><p>Bejelentkezve, mint: <%= link_to current_user.name, user_path(current_user.id) %></p></li>
            <li><%= link_to 'Fiók módosítása',edit_user_registration_path %></li>
            <li><%= link_to 'Kijelentkezés', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to raw("<span class='glyphicon glyphicon-user'> Regisztráció</span>"), '/users/sign_up' %></li>

            <li><%= link_to  raw("<span class='glyphicon glyphicon-log-in'> Bejelentkezés</span>"), new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="jumbotron">
    <div class="container">
        <h1>CookBook</h1>

            <p class="transbox">Készítsd el és értékeld mások receptjeit, vagy küldd be a sajátod.</p>

    </div>
  </div>
<%= render '/layouts/menu' %>

<div class="container">
  <div class="row">
    <div class="container content">
        <%= yield %>
    </div>
  </div>

</div>
</body>
</html>